### ISSUE TITLE
Medium Condensed instance weight

### ISSUE THREAD

**Issue by m4rc1e** [TypeNetwork/Roboto#17]
In #16 I promised to add the Condensed Medium instances.

I've done a quick test using the values found in the original build script, https://github.com/google/roboto/blob/master/scripts/build-v2.py#L141-L142.

We can see that the Roman and Condensed vals differ slightly (Roman=0.35, Condensed=0.4). Unfortunately the avar table is warping the 0.35 val to match the previous Medium. This is making the Condensed Medium a tad lighter than it should be.

![screen shot 2018-07-12 at 14 22 31](https://user-images.githubusercontent.com/7525512/42636044-a8447fe4-85df-11e8-943b-0244fa215cb3.png)

I guess one could increase the value beyond 0.40 to counteract the avar warp... this does feel very hacky though.

If we're happy with the Condensed Medium being a bit thinner, Ill leave this. If anyone has any other suggestions, I'm all ears.

**Comment by cjdunn** [comment]
@davelab6 not sure, but I can look into it, will let you know if I find any better solutions

**Comment by dberlow** [comment]
Not sure why an increase of a value to counteract an avar warp sounds hacky though?

If it takes us to the right instance, it’s just a value poking the right hole in the variable space.

On Jul 16, 2018, at 5:22 PM, CJ Dunn <notifications@github.com> wrote:

@davelab6 not sure, but I can look into it, will let you know if I find any better solutions

**Comment by davelab6** [comment]
Agree with @dberlow 

@cjdunn looking forward to your thoughts :)

**Comment by davelab6** [comment]
Oh I see in the other issue open right now, https://github.com/TypeNetwork/Roboto/issues/16#issuecomment-406662278 , that Marc will attempt this on Monday and likely close both issues :)

**Comment by m4rc1e** [comment]
Right, I've spent my morning on this and haven't been able to come up with anything. I added medium instances, set the vals but the visual output hasn't changed.

@cjdunn can you make an attempt at this?

**Comment by cjdunn** [comment]
@davelab6 I also agree with @dberlow that if we can just change the values then that is ideal. If that doesn't work, we can adjust masters as needed. 

@m4rc1e If this isn't working on your end I can give it a try today, thanks.

**Comment by m4rc1e** [comment]
@cjdunn thanks! really appreciate it

**Comment by davelab6** [comment]
Super, thank you dj!

**Comment by cjdunn** [comment]
I've updated the Roboto-min.designspace file. Pull request is here: https://github.com/TypeNetwork/Roboto/pull/22

**Comment by davelab6** [comment]
Closing as #22 is merged
