### ISSUE TITLE
Stale branches & latest /fonts? 

### ISSUE THREAD

**Issue by davelab6** [TypeNetwork/Roboto#20]
It would be good for TN folks (@cjdunn?) to go over https://github.com/TypeNetwork/Roboto/branches and delete any branches that are merged and no longer needed. 

Also, https://github.com/TypeNetwork/Roboto/tree/master/fonts hasn't been updated in a while, that might need updating?

**Comment by cjdunn** [comment]
@davelab6 at this point all relevant branches have been merged into master so all older branches have been deleted. 

I have just made a temporary branch to add the latest fonts to the "fonts" folder, pull request is here: 
https://github.com/TypeNetwork/Roboto/pull/21

Please feel free to merge and delete the branch (or let me know if you'd rather have me delete it), thanks.

**Comment by davelab6** [comment]
Perfect thank you
