### ISSUE TITLE
Request for "cleaned up corners of the design space"

### ISSUE THREAD

**Issue by davelab6** [TypeNetwork/Roboto#26]
The new 'condensed' named styles, that are newly available in the VF and were not available as static fonts, therefore look different on Android, as you could always request these styles but since they weren't available, the nearest style was used in place. 

E.g. 'Condensed 100' appears to get a lot thinner now, whereas before it was identical to 'Condensed 200' and 'Condensed 300':

<img width="406" alt="screen shot 2018-10-15 at 8 37 56 pm" src="https://user-images.githubusercontent.com/261579/46985803-42eb2000-d0ba-11e8-90eb-a445c8fbbba1.png">

Since people will inevitably use these 'new corners' of the cuboid design space, we should make the effort to ensure they are as good as the other corners.

**Comment by dberlow** [comment]
They all look pretty grey to me;)

**Comment by davelab6** [comment]
Currenly this is out of scope.

**Comment by davelab6** [comment]
I would like to propose quickly dealing with the bad looking width min weight min and max by duplicating the good looking instances as corner masters, so that at the width min the weight axis range is effectively shorter, and in the above image will make the result on the left the same as the right.

**Comment by dberlow** [comment]
I’m just finishing wdth Max wght Max this afternoon. Wght Max wdth min will be done tomorrow?

**Comment by davelab6** [comment]
This is Roboto Classic, not Extremo

**Comment by dberlow** [comment]
Sry nvrmnd

On Jan 9, 2019, at 2:57 PM, Dave Crossland <notifications@github.com> wrote:

This is Roboto Classic, not Extremo

**Comment by sannorozco** [comment]
Yes, we will run some extrapolation tests on Classic Cond.

**Comment by dberlow** [comment]
Please double check. The job relates only to “classic”, is not to do any interpolation at all, or to fix contours. 

The job is to relocate an existing instance in another location, thus eliminating the undesirable extrapolation and that is all.

Clear?

Thanks.

On Jan 11, 2019, at 10:31 AM, Santiago Orozco <notifications@github.com> wrote:

Yes, we will run some extrapolation tests on Classic Cond.

**Comment by dberlow** [comment]
Santiago, 

Here is one cleaned-up Roboto-Classic corner to make sure of one corner first. 

I modified diagonals in both cases, S, s and all related glyphs. 

Please add to make new Variable fonts and point that font to Dave C. 

Let me know if ?

Thanks. 

[RobotoCondensed-Thin-V2DB.ufo.zip](https://github.com/TypeNetwork/Roboto/files/2802719/RobotoCondensed-Thin-V2DB.ufo.zip)
