### ISSUE TITLE
Optimizing preprogram 

### ISSUE THREAD

**Issue by dberlow** [TypeNetwork/Roboto#39]
Mike I noticed while I was separating out the XML of the hints that there are an awful lot of function definitions in the pre-program. I’m wondering if we can easily establish which ones are required by searching the text of the glyph hints, or if you know what’s actual being used, let me know if that’s worth optimizing.

Thanks.

**Comment by mikedug** [comment]
David, I would be very nervous of reducing the function definitions, as I do not have a clear idea, which are needed. Unless this is a big file size saving, and something that is absolutely required, I would recommend leaving as is. 
thanks
mike

**Comment by dberlow** [comment]
Hey Mike, I don’t suggest this calmly, or in any hurry. I’m just interested in the possibilities as we gather up ways to optimize file size.

**Comment by mikedug** [comment]
sure, I can have a look at this. 

I get nervous about removing FN Definitions, the Autohinter is a beast, many functions, I believe rely on or somehow reference others.

we can chat about this as we go along.

mike

**Comment by davelab6** [comment]
This seems to be something that will need to be done in a general purpose, algorithmic way. However, my guess is that I don't want to prioritize this over more important projects, so closing for now.

**Comment by dberlow** [comment]
Agreed. Coincidentally, solving it was one of my last ideas yesterday.
We’ll try it on the upcoming hints of extremo and if that works it’s likely to ttx copy/paste into other fonts that use vtt autohint.


> On Apr 1, 2020, at 8:39 AM, Dave Crossland <notifications@github.com> wrote:
> 

﻿
This seems to be something that will need to be done in a general purpose, algorithmic way. However, my guess is that I don't want to prioritize this over more important projects, so closing for now.
