### ISSUE TITLE
[Review] comparing ttf output from chain against RobotoTTF

### ISSUE THREAD

**Issue by m4rc1e** [TypeNetwork/Roboto#4]
First things first, the quality of the chain and font work is fantastic. Building Roboto using the official buildchain takes a long time. I was super happy to see your chain produce the unhinted fonts in a tenth of the time.

For this review, I'm testing ttfs which have been built by running fontmake on your design space files with the following command:
```
fontmake -m ./Roboto.designspace -o ttf
```

Once the fonts were built, I've compared them against the [official Roboto v2.138 unhinted fonts](https://github.com/google/roboto/releases/tag/v2.138)

So far I've only focused on the Black weight. 

Has the kerning been rebuilt? I don't mind if it has. As long as line lengths remain consistent, I'm happy. I'll figure out a way to test this.

I've used a new [tool](https://github.com/m4rc1e/diffbrowsers) we're currently developing in order to catch visual regressions. I'm attaching a zip of the sample images it has generated as well. If I produce a plot of all the characters and view them across 4 browsers, I can only find 2 issues.

**Acutes have shifted**
*before*
![screen shot 2017-11-23 at 16 50 59](https://user-images.githubusercontent.com/7525512/33183125-812aa0ea-d06e-11e7-83f5-0e0f8dd70bf2.png)

*after*
![screen shot 2017-11-23 at 16 49 32](https://user-images.githubusercontent.com/7525512/33183107-73cf7d12-d06e-11e7-8bad-a11157eb8c2f.png)

**Misplaced mark positions**
*before*
![screen shot 2017-11-23 at 16 54 15](https://user-images.githubusercontent.com/7525512/33183256-08760aa8-d06f-11e7-9a73-c7579fe15949.png)

*after*
![screen shot 2017-11-23 at 16 54 06](https://user-images.githubusercontent.com/7525512/33183274-12941be2-d06f-11e7-943e-e5601a5368fb.png)

Keep this thread open, I need to do further checks.

[TN_Roboto_img.zip](https://github.com/TypeNetwork/Roboto/files/1499872/TN_Roboto_img.zip)

**Comment by davelab6** [comment]
I believe this review is now complete; @m4rc1e please close if so
