### ISSUE TITLE
widths off by 1 upm

### ISSUE THREAD

**Issue by dberlow** [TypeNetwork/Roboto#40]
We notice as we're trying to match output of the newly hinted Roboto vf, that 100's of glyph widths of:
github.com/TypeNetwork/Roboto/blob/master/Hinted%20VTT/MD%20Hints/Sources/Roboto%20Hinted%20Instances/Roboto-Regular.ttf

...that's the original Roboto-Regular.ttf ...don't match, by 1 em unit, the width of the Regular (and default style) of:

github.com/TypeNetwork/Roboto/tree/master/master_ufo/Roboto-Regular.ufo

That's the source of the regular in the vf. 

My impression was that this vf was made compatible between TN and Google, but if required, FB will now get all the exact widths from the sources and script them onto all the sources used to make the vf, and reproduce the vf with matching widths?

Otherwise our hinted output is not going to get as good a match. 

Please advise, thanks. 

dberlow

**Comment by m4rc1e** [comment]
It's going to be impossible to get a 100% perfect match.

Chrome on Windows uses FreeType to render VFs whilst for static fonts it uses DirectWrite.

Before we commit to hinting everything in VTT, it may be best to hint a small sample of glyphs such as "EONASX adhesion $123" and compare this against the version of Roboto we currently serve on Google Fonts.

**Comment by dberlow** [comment]
Hey Mark, 

The whole font is hinted with vtt here; github.com/TypeNetwork/Roboto/blob/master/Hinted%20VTT/MD%20Hints/Fonts/CompatRoboto-min-VF-ship.ttf

We think it’s best to have identical metrics, to the unit per em, but if differences arise because of that we can ignore them?

Cheers, 

David 


> On Jan 9, 2020, at 8:44 AM, Marc Foley <notifications@github.com> wrote:
> 

﻿
It's going to be impossible to get a 100% perfect match.

Chrome on Windows uses FreeType to render VFs whilst for static fonts it uses DirectWrite.

Before we commit to hinting everything in VTT, it may be best to hint a small sample of glyphs such as "EONASX adhesion $123" and compare this against the version of Roboto we currently serve on Google Fonts.

**Comment by dberlow** [comment]
We have replaced the previous version with the new version that has 100% compatible widths.

Mike I think that you can now transfer the hinting you’ve done over to the new version?
