### ISSUE TITLE
Width Compatible Roboto VF / Update Roboto-min-VF —With fixed 1UPM diffs from Roboto-Regular hinted instance

### ISSUE THREAD

**Issue by mikedug** [TypeNetwork/Roboto#41]
Hi Santiago , David
 
I tried exporting the hinting via xml export, from my own hinted VTT font, and importing into the new width compatible font that was posted on GITHUB, by Santiago
 
When I compile VTT reports errors on the following glyphs id’s.  (1118,1347,1348)
 
I get the same errors if I just try run the Autohinter again on the new Width compatible font
 
ERROR MESSAGE *Glyf Pgm, glyph 1118 (Unicode 0x2013), line 4: Composite, Cannot change composite definition in a variation font.
 
*GID 1118  (ENDASH) is a composite of GID 1341 (MINUS).
 
The widths did change on the glyph, by one unit, but I don’t know why the autohinter now chokes on these composites. I can follow up with MS. I could ask a general question about this
 
These glyphs compile fine in the older font, but since the metric change, something is preventing a correct compile.
 
**If these glyphs were made as uniques in the Roboto VF Font I think we could move ahead?** is that possible? **this would be the easiest way forward.** 
 
 ALSO same for the following.
Glyf Pgm, glyph 1347 (Unicode 0x2264), line 5: Composite, Cannot change composite definition in a variation font.
Glyf Pgm, glyph 1348 (Unicode 0x2265), line 5: Composite, Cannot change composite definition in a variation font.

**Comment by sannorozco** [comment]
Updated Roboto-min-VF
—with decomposed endash, lessequal, greaterequal on all masters
