### ISSUE TITLE
MVAR table removal

### ISSUE THREAD

**Issue by dberlow** [TypeNetwork/Roboto#42]
Because Roboto Classic has no changes to the vertical alignments, the MVAR table may be deleted. 

Can this be don't in Fonttools or what?

**Comment by sannorozco** [comment]
Updated VF without MVAR.

**Comment by dberlow** [comment]
Which tool was  used?
Thanks


> On Feb 11, 2020, at 6:13 PM, Santiago Orozco <notifications@github.com> wrote:
> 

﻿
Closed #42.

**Comment by sannorozco** [comment]
Removed MVAR with ttx,
Added atomated ttx remove MVAR each build to sh build script.
