### ISSUE TITLE
fvar coordinates for wght incorrect

### ISSUE THREAD

**Issue by dberlow** [TypeNetwork/Roboto#43]
Hey Mark, 

We need double-check what you mean. 

"	fvar coordinates for wght axis are incorrect. All instance should have values which are multiples of 100. "

All the defined instances have multiples of 100 for values. Thin is 100, light 200 etc. 

For all instances of wght axis to have values that are multiples of 100, 
  a. we would have to add data to the avar to make the wght axis skip from 100 to 200 with no access to the wghts in between from 101-199. This would make a slider of the wght axis have 9 effective values and nothing would happen in between, I think. or, 
  b. we can define the range of wght from, e.g. 100-150 to show the value as 100, from 151-250 as 200, etc. This could make the slider move along over the whole axes as it does now, but there would be sudden changes to the value, as 100 to 150, would show a change of weight but no change to wght value?

Or am I misunderstanding?

**Comment by m4rc1e** [comment]
Hey David,


Unfortunately some of the Condensed instances do not have wght values which are multiples of 100.

```
    <!-- Condensed Light -->
    <NamedInstance flags="0x0" subfamilyNameID="271">
      <coord axis="wght" value="300.0"/>
      <coord axis="wdth" value="75.0"/>
      <coord axis="slnt" value="0.0"/>
    </NamedInstance>

    <!-- Condensed Regular -->
    <NamedInstance flags="0x0" subfamilyNameID="272">
      <coord axis="wght" value="400.0"/>
      <coord axis="wdth" value="75.0"/>
      <coord axis="slnt" value="0.0"/>
    </NamedInstance>

    <!-- Condensed Medium -->
    <NamedInstance flags="0x0" subfamilyNameID="273">
      <coord axis="wght" value="526.3158"/>
      <coord axis="wdth" value="75.0"/>
      <coord axis="slnt" value="0.0"/>
    </NamedInstance>

    <!-- Condensed Bold -->
    <NamedInstance flags="0x0" subfamilyNameID="274">
      <coord axis="wght" value="710.12659"/>
      <coord axis="wdth" value="75.0"/>
      <coord axis="slnt" value="0.0"/>
    </NamedInstance>

    <!-- Condensed Light Italic -->
    <NamedInstance flags="0x0" subfamilyNameID="275">
      <coord axis="wght" value="300.0"/>
      <coord axis="wdth" value="75.0"/>
      <coord axis="slnt" value="-12.0"/>
    </NamedInstance>

    <!-- Condensed Italic -->
    <NamedInstance flags="0x0" subfamilyNameID="276">
      <coord axis="wght" value="400.0"/>
      <coord axis="wdth" value="75.0"/>
      <coord axis="slnt" value="-12.0"/>
    </NamedInstance>

    <!-- Condensed Medium Italic -->
    <NamedInstance flags="0x0" subfamilyNameID="277">
      <coord axis="wght" value="526.3158"/>
      <coord axis="wdth" value="75.0"/>
      <coord axis="slnt" value="-12.0"/>
    </NamedInstance>

    <!-- Condensed Bold Italic -->
    <NamedInstance flags="0x0" subfamilyNameID="278">
      <coord axis="wght" value="710.12659"/>
      <coord axis="wdth" value="75.0"/>
      <coord axis="slnt" value="-12.0"/>
    </NamedInstance>
```
_Font from: https://github.com/TypeNetwork/Roboto/tree/master/Hinted%20VTT/MD%20Hints/Fonts_

For instance, I would expect the Medium to be 500 and the Bold to be 700.

The normal widths are fine though.

Since the wght values are mapped to css `font-weight` this will cause problems for existing users.

**Comment by dberlow** [comment]
Oh my, Thanks. 

Santiago, the design space file needs changes to the wght values of:
Italic and Condensed,
   Mediums must be 500
   Bolds must be 700
Let me know thanks, 
David

**Comment by sannorozco** [comment]
Updated fvar locations.
