### ISSUE TITLE
File size diet test: issue with features, groups, kerning

### ISSUE THREAD

**Issue by sannorozco** [TypeNetwork/Roboto#48]
**Features**
Roboto has a [lot of opentype features](https://github.com/TypeNetwork/Roboto/blob/harfbuzz-test/master_ufo/features.fea), so how will these be updated on the fly? This is a big one, since features needs to be compiled for each master, and I’m not sure if HarfBuzz can add the new rendered glyphs to its features?

**Groups & Kerning**
If say, /Aacute is rendered, how it will be added to the /A left and right groups to apply the kerning?

**Comment by khaledhosny** [comment]
Harfbuzz will decompose the Unicode character for /Aacute into two glyphs /A and /acutecomb, so kerning and other OpenType features for /A will apply (some lookups will need IgnoreMarks lookup flag for this to work).

HarfBuzz does not create new glyphs, it will be basically essentially as if the input was /A/acutecomb.

The tricky part is when there are OpenType feature specific to the composite glyph, e.g. a kerning pair specific to /Aacute, as this will need to be done as a contextual positioning lookup by the font (but it should be possible to do this by a script that examines the existing sources and build such positioning data).

This also does not depend on glyph names in anyway, HarfBuzz applies Unicode normalization which uses Unicode code points.

**Comment by brawer** [comment]
@sannorozco, OpenType has a [lookupflag](http://adobe-type-tools.github.io/afdko/OpenTypeFeatureFileSpecification.html#4.d) which might come in handy here, especially if you want to keep your `GPOS` tables small.
