### ISSUE TITLE
Roboto Stat Table

### ISSUE THREAD

**Issue by dberlow** [TypeNetwork/Roboto#52]
Please advise here that styles shown bold are to be in stat table, and any others.

Shared:
https://docs.google.com/document/d/105taihvuc3CA_qPi4G1-7A1v5QmMSJ6dBwXmpBrrdTA/edit?usp=sharing

**Comment by davelab6** [comment]
36 styles: 9 weights, 100 .. 900, in both normal and condensed, for roman and italic.

**Comment by dberlow** [comment]
I've updated this for nine weights of Normal and Italic, Condensed and Itailc
Looking for 
1. style name for 300, between Thin and Regular,
2. confirmation of SemiBold=600, ExtraBold=800.

**Comment by davelab6** [comment]
300 = Light

**Comment by davelab6** [comment]
I updated the Google Doc

**Comment by dberlow** [comment]
I've completed the changes to the Google Doc, and believe it's definitive for Santiago's use.

Please confirm, thanks.

**Comment by sannorozco** [comment]
This is still in the works, still not getting it right.

**Comment by davelab6** [comment]
Per https://twitter.com/axis_praxis/status/1250818656281464838?s=19 I'd like to revisit this

**Comment by thlinard** [comment]
https://github.com/google/fonts/issues/2391 could be helpful.

**Comment by m4rc1e** [comment]
Stat was update in #79
