### ISSUE TITLE
Clean up repo 

### ISSUE THREAD

**Issue by davelab6** [TypeNetwork/Roboto#55]
@m4rc1e please can you point to the best docs on what we expect in terms of repo hygiene? :)

**Comment by sannorozco** [comment]
Cleaned up repo in branch “delivery-review”

**Comment by m4rc1e** [comment]
Thank you for making the changes in a new branch and not the new repo.

Please could you make sure the new branch look similar to [Inconsolata](https://github.com/googlefonts/Inconsolata). This repo will have the following structure once it's done.

```
.
├── AUTHORS.txt
├── CONTRIBUTORS.txt
├── DESCRIPTION.en_us.html
├── FONTLOG.txt
├── OFL.txt
├── README.md
├── documentation
│   ├── font-export.png
│   ├── img
│   ├── inconsolata-diagonals.ai
│   ├── inconsolata-features.pdf
│   └── inconsolata-test.txt
├── fonts
│   ├── otf
│   ├── ttf
│   └── variable
├── requirements.txt
└── sources
    ├── Inconsolata.glyphs
    ├── build.sh
    ├── stat.stylespace
    └── vtt_hinting.ttx
```
