### ISSUE TITLE
Roboto[wght,wdth,ital].ttf gasp table

### ISSUE THREAD

**Issue by dberlow** [TypeNetwork/Roboto#56]
There are two choices, 
1. the original from Roboto-Regular.ttf
2. the recommended one that's been used since VTT was employed.

The gasp table is being copied into the font by script using ttx, after the vf is build, and before it's hinted.

Gasp table 2 above is currently used, but it's a simple change if on review it's not desired.

**Comment by sannorozco** [comment]
This is fixed and implemented in build, option 1
