### ISSUE TITLE
Delivery complete

### ISSUE THREAD

**Issue by dberlow** [TypeNetwork/Roboto#62]
Marc and Dave,

I, Mike and Santiago believe we’ve delivered.

We’re standing by for any comments, questions or requests.

Cheers,
David

**Comment by m4rc1e** [comment]
Please don't merge any wip work into the master branch until it's been reviewed. We now have a master that can't build properly. 


@sannorozco We've hit a couple of errors. Please do the following:

- include `gftools` in the requirements.txt file (stops fonts from being built)
- Include `sources/Roboto-min.stylespace` (stops fonts from being built)
- Remove `sources/HintingSource`. `sources/vtt-hinting.ttx` should be our single source of truth.
- Drop the [maxp fixes](https://github.com/TypeNetwork/Roboto/blob/master/sources/build-min.sh#L17-L25) in build-min.sh. vttLib will generate this table for you
- Move `fonts/fixes` dir `to sources/fixes`

I'll recheck the fonts everything once this is done.

**Comment by sannorozco** [comment]
@m4rc1e updated repo with these fixes. Let me know if more is needed.

**Comment by m4rc1e** [comment]
• Delete https://github.com/TypeNetwork/Roboto/blob/master/OFL.txt. 
• In `docs/` the dirs `Compare/`, `Hinted VTT/` and `Roboto Hinted Instances/` are redundant + they're not docs. They should be deleted
• `fonts/Roboto-vf.ttf` is 2 years old. Is this an old font we've forgotten to delete?

**Comment by sannorozco** [comment]
- Deleted OFL.txt and dirs.

- About `fonts/Roboto-vf.ttf`, this VF has been there since the beginning, I believe it’s for comparison with the current Roboto? And the new is the improved. So confirming, is it ok with you if deleted?

**Comment by m4rc1e** [comment]
> I believe it’s for comparison with the current Roboto? 

I don't use it for comparisons. I use the tagged fonts in google/roboto, https://github.com/google/roboto/releases/tag/v2.136

**Comment by dberlow** [comment]
As far as I know, fonts/Roboto-vf.ttf Should be deleted.


> On Apr 1, 2020, at 10:34 AM, Marc Foley <notifications@github.com> wrote:
> 

﻿
I believe it’s for comparison with the current Roboto?

I don't use it for comparisons. I use the tagged fonts in google/roboto, https://github.com/google/roboto/releases/tag/v2.136
