### ISSUE TITLE
License | Update for clarity

### ISSUE THREAD

**Issue by staghouse** [TypeNetwork/Roboto#67]
It is not clear what License this project and fonts are actually covered under. The README says Apache but the repo has a OFL license as well.

**Comment by davelab6** [comment]
@staghouse sorry my delay on this. This project is OFL.

**Comment by davelab6** [comment]
Actually, sorry, I forgot that since the Google Fonts eng team wanted to publish this font with the VF axes and then do the OFL upgrade, that will come later. I'll make a PR to update the README

**Comment by staghouse** [comment]
Thanks for the update!

**Comment by davelab6** [comment]
Readme says Apache, closing
