### ISSUE TITLE
Build broken

### ISSUE THREAD

**Issue by m4rc1e** [TypeNetwork/Roboto#81]
Latest commit https://github.com/TypeNetwork/Roboto/commit/e35e4c071d4c6fe235b900ee3aecf11321f785cc has broken the build. When running `sh sources/build.sh`, I get the following traceback:

```
(venv) Marcs-Air:roboto marcfoley$ sh sources/build.sh 
fontmake: Error: In 'sources/Roboto.designspace' -> 'sources/RobotoCondensed-LightItalic.ufo': Reading UFO source failed: 'fontinfo.plist' could not be read on <osfs '/Users/marcfoley/Type/upstream_families/Roboto/sources/RobotoCondensed-LightItalic.ufo'>: StartTag: invalid element name, line 223, column 2 (fontinfo.plist, line 223)
```

Please don't push to master! make your changes on a new branch and open a PR.

We have a CI/CD which will build and test the fonts for each PR. If we had done these changes in a PR, we wouldn't have merged since the fonts can't build.

**Comment by sannorozco** [comment]
PR ready for review, fixed plist conflict
