### ISSUE TITLE
Mark glyphs with incorrect contour directions

### ISSUE THREAD

**Issue by m4rc1e** [TypeNetwork/Roboto#86]
If a mark glyph is used a component in another glyph and its contour orientation differs from the base glyph, the marks will appear lighter in OS X. For this family, I can see that the [double grave accent's](https://www.fileformat.info/info/unicode/char/030f/index.htm) has this issue (there may be more).

![roboto1](https://user-images.githubusercontent.com/7525512/98812329-2f861c80-241a-11eb-9cbd-ddb8d73f454f.gif)

_Ȑ double grave appears lighter. Issue also happens in Ѷ ѷ Ȁ ȁ Ȅ ȅ Ȉ ȉ Ȍ ȍ Ȑ ȑ Ȕ ȕ Ȕ_

To solve this issue, we must do the following:

- Find all mark glyphs which are used in composite glyphs whose contour directions are incorrect
- Fix the orientation for the mark glyphs we found above
- Rehint the mark glyphs
- Bump version and repush

Imo this is a blocker and we must solve this issue before we can release the family. We discovered this issue whilst reviewing Asap, https://github.com/TypeNetwork/Asap/issues/6

cc @davelab6 @dberlow @moyogo

**Comment by dberlow** [comment]
According to the sources, (U+030F) reversal includes Roman and italic.

**Comment by mikedug** [comment]
the contours for (U+030F) , compared to Unicode 0210, look to be the same orientation in VTT in the Roboto Variable. Am I missing something?[]
![0X30F](https://user-images.githubusercontent.com/55890745/98822328-9dd1db80-2428-11eb-8805-5417ad7ed578.png)
(url)

**Comment by m4rc1e** [comment]
> the contours for (U+030F) , compared to Unicode 0210, look to be the same orientation in VTT in the Roboto Variable. Am I missing something?[]

If we inspect uni210, the base component "R" is anticlockwise, whilst the mark component "double tilde" is clockwise.

**Comment by mikedug** [comment]
ok, thanks. I see the R as clockwise and the accent as anti-clockwise, in the illustration above.

**Comment by davelab6** [comment]
But, either way, they are opposite directions, but they should be the same directions. 

@m4rc1e please can you file a fontbakery issue to check for this?

**Comment by dberlow** [comment]
If these need to be fixed by FB, let me know.

**Comment by davelab6** [comment]
I believe this is a minor production issue, which will take Marc 4-8 hours to do, and so with other high priority FB projects going on, its best for Marc to do :)
